- name: Assistant
  hosts: all
  tasks:
    - become: true
      community.general.pacman:
        state: installed
        name:
          - bluez
          - bluez-utils
          - dbus-broker

    - name: start bluetooth service
      become: true
      ansible.builtin.service:
        name:  bluetooth
        enabled: yes
        state: started

    - name: start dbus-broker
      become: true
      ansible.builtin.service:
        name:  dbus-broker
        enabled: yes
        state: started
