version: '3'

include:
  - ./services/traefik.yaml
  - ./services/photoprism.yaml
  - ./services/assistant/compose.yaml
  - ./services/syncthing.yaml
  - ./services/kavita.yaml
  - ./services/rsync/compose.yml
