# Default login: admin / admin
version: "3.8"
services:
  grafana:
    image: grafana/grafana-enterprise
    restart: unless-stopped
    labels:
      - "traefik.http.routers.grafana.rule=Host(`grafana.home.emadelsaid.com`)"
    logging:
      driver: journald

    user: '0'
    volumes:
      - /home/docker/services/grafana:/var/lib/grafana

  node-exporter:
    image: prom/node-exporter:latest

    restart: unless-stopped
    logging:
      driver: journald

    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro

    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'

    expose:
      - 9100

  prometheus:
    image: prom/prometheus:latest

    restart: unless-stopped
    logging:
      driver: journald

    user: '0'
    volumes:
      - /home/docker/services/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /home/docker/services/prometheus/data:/prometheus

    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'

    expose:
      - 9090
