services:
  ai:
    image: ghcr.io/open-webui/open-webui:main
    restart: unless-stopped
    labels:
      - "traefik.http.routers.ai.rule=Host(`ai.home.emadelsaid.com`)"
      - "traefik.http.services.ai.loadbalancer.server.port=8080"
    volumes:
      - /home/docker/services/ai:/app/backend/data
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
