# After installation get the password using:
# docker compose exec -it gitlab grep 'Password:' /etc/gitlab/initial_root_password
# Or reset it using
# docker compose exec -it gitlab gitlab-rake "gitlab:password:reset
services:
  gitlab:
    image: gitlab/gitlab-ee:18.4.0-ee.0
    restart: unless-stopped
    hostname: 'gitlab.home.emadelsaid.com'
    labels:
      - "traefik.http.routers.gitlab.rule=Host(`gitlab.home.emadelsaid.com`)"
      - "traefik.http.services.gitlab.loadbalancer.server.port=80"
    logging:
      driver: journald
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.home.emadelsaid.com'
        gitlab_rails['gitlab_shell_ssh_port'] = 2424
    ports:
      - '2424:22'
    volumes:
      - '/home/docker/services/gitlab/config:/etc/gitlab'
      - '/home/docker/services/gitlab/logs:/var/log/gitlab'
      - '/home/docker/services/gitlab/data:/var/opt/gitlab'
    shm_size: '256m'
  # Add a runner from setting and add this prefix before the registeration command
  # docker compose exec -it gitlab-runner <the-command>
  gitlab-runner:
    image: gitlab/gitlab-runner:ubuntu-6398b613
    restart: unless-stopped
    logging:
      driver: journald
    volumes:
      - '/home/docker/services/gitlab-runner:/etc/gitlab-runner/'
