version: '3'

services:
  whoami:
    image: traefik/whoami
    restart: always
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)"
    logging:
      driver: journald
