version: "3"
services:
  rsync:
    build: .
    restart: unless-stopped
    logging:
      driver: journald
    environment:
      # Make sure to set SRC to the "user@server-ip-address:/path/to/files"
      - RSYNC_SRC
      - WAIT=3600
      - DST=/downloads
    volumes:
      - /home/docker/services/rsync/downloads:/downloads
      - /home/docker/services/rsync/ssh:/root/.ssh
