#!/bin/sh

# Get server key
SRV=`echo $RSYNC_SRC | sed 's/:.*//' | sed 's/.*@//'`
ssh-keyscan -t rsa $SRV > /root/.ssh/known_hosts

# Generate ssh key
ssh-keygen -t ed25519 -f /root/.ssh/id_ed25519 -q -N ""
echo "Public key: `cat /root/.ssh/*.pub`"

# Execute rsync and wait for an hour
while [ true ]
do
    rsync --remove-source-files --append -azv $RSYNC_SRC $DST
    sleep $WAIT
done
